% This function determines the  effect of aerodynamic forces on the
% body.

function F_aero = AerodynamicForces(q,F,Lf,Lr,a,b)

theta = q(4);
phi = q(5);
psi = q(6);
alpha = q(7);
alpha_l = q(8);
alpha_r = q(9);

F_aero = ...
[2*sin(psi)*sin(theta), sin(psi)*sin(theta), sin(psi)*sin(theta), -2*cos(psi), -cos(psi), -cos(psi), -cos(psi), sin(psi)*cos(theta);...
    -2*cos(psi)*sin(theta), -cos(psi)*sin(theta), -cos(psi)*sin(theta), -2*sin(psi), -sin(psi), -sin(psi), -sin(psi), -cos(psi)*cos(theta);...
    2*cos(theta), cos(theta), cos(theta), 0, 0, 0, 0, -sin(theta);...
    0, -Lr*(cos(phi) - 1)*cos(theta)^2 - Lr, Lr*(cos(phi) - 1)*cos(theta)^2 + Lr, 0, sin(phi)*Lr*cos(theta), -sin(phi)*Lr*cos(theta), 0, 0;...
    -2*cos(phi)*a*cos(theta), sin(phi)*Lr*cos(theta)*sin(theta) + cos(phi)*b*cos(theta), -sin(phi)*Lr*cos(theta)*sin(theta) + cos(phi)*b*cos(theta), 2*sin(phi)*a, cos(phi)*sin(theta)*Lr - sin(phi)*b, -cos(phi)*sin(theta)*Lr - sin(phi)*b, 0, 0;...
    -2*cos(phi)*a*sin(theta), -sin(phi)*Lr*cos(theta)^2 + cos(phi)*b*sin(theta) + sin(phi)*Lr, sin(phi)*Lr*cos(theta)^2 + cos(phi)*b*sin(theta) - sin(phi)*Lr, 0, -Lr*cos(theta), Lr*cos(theta), 0, 0;...
    0, 0, 0, 0, 0, 0, 0, 0;...
    0, 0, 0, 0, 0, 0, 0, 0;...
    0, 0, 0, 0, 0, 0, 0, 0]*F;


